# WhatATheme
markdown: kramdown

# URL of the Site
url: 'Profile'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nahid Hasan
# Description of the Site
description: Junior DevOps Engineer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://drive.google.com/file/d/1Zw_bJYLPk1bAglN2RZtkaZZQ-LRE51o9/view?usp=sharing

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: nahid.hasancseru@gmail.com
facebook_username: nahids06
twitter_username: HasanNahid17377
instagram_username: halcyonnahid
linkedin_username: md-nahid-hasan-26290b1b6
github_username:  NahidCSERU
youtube_channel_id: UCx_fUabjOhqyXhwIDet-pOQ
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Nahid 
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: My name is Nahid Hasan. I completed my Bsc in computer science and engineering in 2023(august). I would like to obtain a challenging position in DevOps where my technical and interpersonal skills can be utilized to benefit both me and Organization. I have some deployment experience with docker. I have also collaboration and automation CI/CD pipeline with git and Github Actions.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/NahidCSERU

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
